ignoredBuiltDependencies:
  - oxc-resolver
  - sharp

nodeLinker: isolated

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - spawn-sync ## @v1, dependency of web-ext-run

savePrefix: ""

updateNotifier: false
