allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  oxc-resolver: false
  sharp: false
  spawn-sync: true ## @v1, dependency of web-ext-run

ignorePatchFailures: false

nodeLinker: isolated

patchedDependencies:
  "@base-ui/react": patches/@base-ui__react.patch
  lodash: patches/lodash.patch

savePrefix: ""

updateNotifier: false
