name: Label Pull Requests

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: Apply path labels
    runs-on: ${{ vars.RUNNER_LABEL || 'ubuntu-24.04' }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
